CREATE TABLE accounts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name   VARCHAR(120)  NOT NULL,
    cpf             VARCHAR(11)   NOT NULL,
    bank_code       INTEGER       NOT NULL,
    bank_name       VARCHAR(120)  NOT NULL,
    branch          VARCHAR(4)    NOT NULL,
    account_number  VARCHAR(20)   NOT NULL,
    CONSTRAINT uk_accounts_cpf UNIQUE (cpf)
);
