CREATE TABLE transfers (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_cpf           VARCHAR(11)    NOT NULL,
    source_account         VARCHAR(30)    NOT NULL,
    destination_bank_code  INTEGER        NOT NULL,
    destination_bank_name  VARCHAR(120)   NOT NULL,
    destination_branch     VARCHAR(4)     NOT NULL,
    destination_account    VARCHAR(30)    NOT NULL,
    amount                 NUMERIC(19,2)  NOT NULL,
    type                   VARCHAR(20)    NOT NULL,
    fee_applied            NUMERIC(19,2)  NOT NULL,
    total_debited          NUMERIC(19,2)  NOT NULL,
    scheduled_date         DATE           NOT NULL,
    requested_at           TIMESTAMP      NOT NULL
);

CREATE INDEX idx_transfers_customer_cpf ON transfers (customer_cpf);
