CREATE TABLE clientes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(120)  NOT NULL,
    cpf              VARCHAR(11)   NOT NULL,
    data_nascimento  DATE          NOT NULL,
    estado_civil     VARCHAR(20)   NOT NULL,
    sexo             VARCHAR(20)   NOT NULL,
    CONSTRAINT uk_clientes_cpf UNIQUE (cpf)
);

CREATE INDEX idx_clientes_cpf ON clientes (cpf);
