CREATE TABLE compras (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente                 BIGINT         NOT NULL,
    cpf_cliente                VARCHAR(11)    NOT NULL,
    data_solicitacao           TIMESTAMP      NOT NULL,
    tipo_moeda                 VARCHAR(3)     NOT NULL,
    valor_moeda_estrangeira    NUMERIC(19,4)  NOT NULL,
    valor_cotacao              NUMERIC(19,6)  NOT NULL,
    valor_total_operacao       NUMERIC(19,2)  NOT NULL,
    numero_agencia_retirada    VARCHAR(4)     NOT NULL
);

CREATE INDEX idx_compras_cpf_cliente ON compras (cpf_cliente);
